### PR TITLE
PDF to DOCX using LibreOffice, fixes #425

### LINKED ISSUE #425: Cannot convert PDF to DOCX using LibreOffice
**Describe the bug**
Translating from PDF to DOCX via LibreOffice is not working - error reported - 'Something went wrong!'.   Please note I have sucessfully converted an image type to other image type, the issue seems LibreOffice.

**Steps to reproduce the behavior:**

1. Go to ConvertX ( a docker instance on TrueNAS Core, settings already preset,  HTTP Allowed is enabled)
2. Upload a PDF
3. Select LibreOffice to translate to DOCX
4. See error below

**Error Log:**

```
2025-10-23 10:54:41.781571+00:00ConvertX v0.15.0
2025-10-23 10:54:41.859819+00:00🦊 Elysia is running at http://localhost:3000
2025-10-23 10:54:41.869731+00:00Debian GNU/Linux 13 (trixie)
2025-10-23 10:54:41.869797+00:00resvg v0.45.1
2025-10-23 10:54:41.870014+00:00ImageMagick 7.1.1-43 Q16 x86_64 22550 https://imagemagick.org
2025-10-23 10:54:41.870131+00:00XeTeX 3.141592653-2.6-0.999996 (TeX Live 2025/dev/Debian)
2025-10-23 10:54:41.870189+00:00assimp Version 5.4 -debug -shared -st (GIT commit 0)
2025-10-23 10:54:41.870270+00:00djxl v0.11.1 [AVX2,SSE4,SSE2]
2025-10-23 10:54:41.870329+00:00GraphicsMagick 1.4 snapshot-20250331 Q16 http://www.GraphicsMagick.org/
2025-10-23 10:54:41.870378+00:00pandoc 3.1.11.1
2025-10-23 10:54:41.870430+00:00dasel version v2.8.1-1
2025-10-23 10:54:41.870480+00:00potrace 1.16. Copyright (C) 2001-2019 Peter Selinger.
2025-10-23 10:54:41.870549+00:00Bun v1.2.2
2025-10-23 10:54:41.870650+00:00msgconvert (libemail-outlook-message-perl) is not installed
2025-10-23 10:54:41.870687+00:00libheif v1.19.8
2025-10-23 10:54:41.870731+00:00vips-8.16.1
2025-10-23 10:54:41.870789+00:00ffmpeg version 7.1.2-0+deb13u1 Copyright (c) 2000-2025 the FFmpeg developers
2025-10-23 10:54:41.870843+00:00Inkscape 1.4 (e7c3feb100, 2024-10-09)
2025-10-23 10:54:41.897714+00:00ebook-convert (calibre 8.5.0)
2025-10-23 10:54:41.937257+00:00LibreOffice 25.2.3.2 520(Build:2)
2025-10-23 10:56:08.449739+00:00jobId set to: 6
2025-10-23 10:56:29.312041+00:00stderr: Warning: failed to launch javaldx - java may not function correctly
2025-10-23 10:56:29.312084+00:002025-10-23T10:56:29.312084994Z
2025-10-23 10:56:29.312094+00:00(process:143): dconf-CRITICAL **: 11:56:29.303: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly.
2025-10-23 10:56:29.312113+00:00LibreOffice 25.2 - Fatal Error: The application cannot be started. 
2025-10-23 10:56:29.312122+00:00User installation could not be completed. 
2025-10-23 10:56:29.312130+00:002025-10-23T10:56:29.312130010Z
2025-10-23 10:56:29.312138+00:00Failed to convert ./data/uploads/1/6/fge_50255280_5110363_15-06-2025_0_Y.pdf from pdf to docx using libreoffice. error: Error: Command failed: soffice --headless --convert-to docx --outdir data/output/1/6 ./data/uploads/1/6/fge_50255280_5110363_15-06-2025_0_Y.pdf
2025-10-23 10:56:29.312165+00:00Warning: failed to launch javaldx - java may not function correctly
2025-10-23 10:56:29.312174+00:002025-10-23T10:56:29.312174224Z
2025-10-23 10:56:29.312182+00:00(process:143): dconf-CRITICAL **: 11:56:29.303: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly.
2025-10-23 10:56:29.312198+00:00LibreOffice 25.2 - Fatal Error: The application cannot be started. 
2025-10-23 10:56:29.312207+00:00User installation could not be completed. 
2025-10-23 10:56:29.312216+00:002025-10-23T10:56:29.312216595Z
```

- [X] I am accessing ConvertX over HTTPS or have `HTTP_ALLOWED=true`

### PR DESCRIPTION
**Pull request by ToniRos**
Solution to conversión from PDF to DOCX reported in issue #425
The quotation marks in the infilter that caused problems with execfile have been removed, and the writer_pdf_import filter has been enabled.

---
## Summary by cubic
Fixes PDF input conversions (e.g., PDF to DOCX/TXT) by enabling the LibreOffice writer_pdf_import filter and removing quotes around --infilter to prevent execFile errors; also avoids filters when exporting to PDF. Addresses issue #425.

<sup>Written for commit 3ed9fabc800e1eed7c76fde86f267a460cfea4af. Summary will update on new commits.</sup>

### CODE REVIEW

File: src/converters/libreoffice.ts [hunk 1]
```diff
@@ -102,7 +102,7 @@ const filters: Record<FileCategories, Record<string, string>> = {
     odt: "writer8",
     ott: "writer8_template",
     pages: "Apple Pages",
-    // pdf: "writer_pdf_import",
+    pdf: "writer_pdf_import",
```
[the remark this answers is not in the document]
Comment (ToniRos) [reply src/converters/libreoffice.ts:105]: This is adressed with this new check in getFilters libreoffice.ts
```
  if (converto === "pdf") {
    return [null, null];
```

File: tests/converters/libreoffice.test.ts [hunk 2]
```diff
@@ -63,7 +63,7 @@ test("invokes soffice with --headless and outdir derived from targetPath", async
   expect(cmd).toBe("soffice");
   expect(args).toEqual([
     "--headless",
-    `--infilter="MS Word 2007 XML"`,
+    `--infilter=MS Word 2007 XML`,
```
Comment (C4illin) [inline tests/converters/libreoffice.test.ts]:
```suggestion
    "--infilter=MS Word 2007 XML",
```

File: src/converters/libreoffice.ts [hunk 3]
```diff
@@ -148,7 +150,7 @@ export function convert(
   const [inFilter, outFilter] = getFilters(fileType, convertTo);
 
   if (inFilter) {
-    args.push(`--infilter="${inFilter}"`);
+    args.push(`--infilter=${inFilter}`);
```
Comment (C4illin) [inline src/converters/libreoffice.ts:153]:
```suggestion
    args.push("--infilter=${inFilter}");
```
