### PR TITLE
Fix timezone display in history page

### LINKED ISSUE #408: The time zone displayed in the "history" is incorrect
I am running software in a Docker container and using /etc/localtime:/etc/localtime:ro to make the container use the system time zone. However, the time zone displayed in the "history" is incorrect, while the time zone inside the container is correct.

### PR DESCRIPTION
**Pull request by majiayu000**
## Summary
Fixes #408 - History page displays incorrect timezone when TZ environment variable is set.

**Root cause:** `toLocaleTimeString(LANGUAGE)` was used without passing `timeZone` option, so it didn't respect the TZ environment variable.

**Changes:**
- Add `TIMEZONE` export from `env.ts` using `process.env.TZ`
- Pass `timeZone: TIMEZONE` option to `toLocaleString` in history.tsx
- Changed from `toLocaleTimeString` to `toLocaleString` to show both date and time

## Test plan
- Set `TZ=America/New_York` in environment
- Create a conversion job
- Check history page - timestamp should reflect the configured timezone

---
## Summary by cubic
History page timestamps now respect the TZ environment variable and render times in the configured timezone.

- **Bug Fixes**
  - Export TIMEZONE from env.ts using process.env.TZ.
  - Pass { timeZone: TIMEZONE } to toLocaleTimeString in history.tsx.

<sup>Written for commit 4312968c8e4de51348a68afadd9f008394f2ea2b. Summary will update automatically on new commits.</sup>

### CODE REVIEW

File: src/helpers/env.ts [hunk 1]
```diff
@@ -23,3 +23,5 @@ export const MAX_CONVERT_PROCESS =
 
 export const UNAUTHENTICATED_USER_SHARING =
   process.env.UNAUTHENTICATED_USER_SHARING?.toLowerCase() === "true" || false;
+
+export const TIMEZONE = process.env.TZ || undefined;
```
Comment (SAHIL-Sharma21) [inline src/helpers/env.ts:27]: Can we change the environment name from TZ to something more meaningful, or write the full variable name?

Comment (C4illin) [reply src/helpers/env.ts:27]: TZ is a linux default, I think we should keep it as is :)

**Comment by majiayu000** [comment]
Thanks for the review\! As @C4illin mentioned, TZ is the standard Linux environment variable for timezone, so I'll keep it as is.

File: src/helpers/env.ts (hunk 1 above)
Comment (SAHIL-Sharma21) [reply src/helpers/env.ts:27]: Okay, got it!

File: src/pages/history.tsx [hunk 2]
```diff
@@ -129,7 +129,11 @@ export const history = new Elysia().use(userService).get(
                             />
                           </svg>
                         </td>
-                        <td safe>{new Date(job.date_created).toLocaleTimeString(LANGUAGE)}</td>
+                        <td safe>
+                          {new Date(job.date_created).toLocaleString(LANGUAGE, {
```
Comment (C4illin) [inline src/pages/history.tsx]:
```suggestion
                          {new Date(job.date_created).toLocaleTimeString(LANGUAGE, {
```

Comment (C4illin) [reply src/pages/history.tsx]: I think just time is enough here

**Comment by C4illin** [comment]
Missed that you intentionally added both date and time, but since the default auto delete is 24h I think showing date is unnecessary

**Comment by majiayu000** [comment]
Pushed a Prettier formatting fix for  to the PR branch. Lint should pass now.

**Comment by majiayu000** [comment]
Pushed a Prettier formatting fix for `src/pages/history.tsx` to the PR branch. Lint should pass now.
